@api = http://localhost:4000/usuarios

GET  {{api}}
###
POST {{api}}
Content-Type: application/json

{
        "username": "qqqqqqqqqq",
        "password": "1234567890",
        "works": 0,
        "followers": 0,
        "follows": 0,
        "premium": 1,
        "description": "rweqrewerwqsdfasdfacxczv"
}
###
GET {{api}}/11

###

DELETE {{api}}/9

###
PUT {{api}}/11
Content-Type:application/json

{
        "username": "UsuarioPerdiLaCuenta",
        "password": "4554788721",
        "works": 0,
        "followers": 0,
        "follows": 0,
        "premium": 0,
        "description": "Si sale bien termine la api de prueba"
}
